[package]
name = "create-account"
version = "0.1.0"
edition = "2021"

[features]
bpf-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.9.0"
pinocchio-log = "0.5.0"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"
